"use client";

import { useSearchParams } from "next/navigation";

import ScoreCard from "@/components/ScoreCard";

export default function ReportPage() {

    const searchParams =
        useSearchParams();

    const data =
        searchParams.get("data");

    if (!data) {

        return (
            <main className="min-h-screen bg-black text-white flex items-center justify-center">
                Report not found
            </main>
        );
    }

    const report =
        JSON.parse(
            decodeURIComponent(data)
        );

    return (
        <main className="min-h-screen bg-black text-white px-6 py-12">

            <div className="max-w-6xl mx-auto">

                {/* Header */}
                <div className="mb-12">

                    <h1 className="text-5xl font-bold">
                        AI Interview Report
                    </h1>

                    <p className="text-gray-400 mt-4 text-lg">
                        Personalized performance analysis
                        generated by your AI interview system.
                    </p>

                </div>

                {/* Score */}
                <div className="bg-white text-black rounded-3xl p-10 mb-10">

                    <h2 className="text-2xl font-semibold">
                        Overall Score
                    </h2>

                    <p className="text-7xl font-bold mt-4">
                        {report.overall_score}/10
                    </p>

                </div>

                {/* Cards */}
                <div className="grid md:grid-cols-2 gap-6 mb-10">

                    <ScoreCard
                        title="Strengths"
                        items={report.strengths}
                    />

                    <ScoreCard
                        title="Weak Areas"
                        items={report.weak_areas}
                    />

                </div>

                {/* Recommendations */}
                <div className="mb-10">

                    <ScoreCard
                        title="Recommendations"
                        items={report.recommendations}
                    />

                </div>

                {/* Final Feedback */}
                <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8">

                    <h2 className="text-2xl font-semibold mb-4">
                        Final Feedback
                    </h2>

                    <p className="text-gray-300 leading-relaxed text-lg">
                        {report.final_feedback}
                    </p>

                </div>

            </div>

        </main>
    );
}